### ISSUE TITLE
When accessing xuanran001.com we run into a cached page

### ISSUE THREAD

**Issue by xxd3vin** [xxd3vin/workspace#1]
## Summay

访问xuanran001首页，出现的是旧的页面（缓存）

登录0.64，pgsql已经挂了

```
[root@database chenyang]# /etc/init.d/postgresql-9.3 status
postgresql-9.3 dead but pid file exists
```

从07-14凌晨01:30开始出现故障，这是0.60上的`sling/logs/error.log`。
```
14.07.2015 01:30:30.783 *INFO* [qtp1476737836-3716] logs/request.log 14/Jul/2015:01:30:30 +0800 [6528] <- 200 - 43ms
14.07.2015 01:30:30.783 *INFO* [qtp1476737836-3716] logs/access.log 192.168.0.61 - anonymous 14/Jul/2015:01:30:30 +0800 "GET /sysop.shmodellib.getModel
Category2 HTTP/1.1" 200 30886 "-" "Drupal (+http://drupal.org/)"
14.07.2015 01:30:36.683 *ERROR* [192.168.0.61 [1436808628443] GET /sysop.shmodellib.detail HTTP/1.1] org.apache.jackrabbit.core.util.db.ConnectionHelpe
r Failed to execute SQL (stacktrace on DEBUG log level): org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
14.07.2015 01:30:36.785 *ERROR* [192.168.0.61 [1436808628443] GET /sysop.shmodellib.detail HTTP/1.1] org.apache.jackrabbit.core.util.db.ConnectionHelpe
r Failed to execute SQL (stacktrace on DEBUG log level): org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
14.07.2015 01:30:36.786 *ERROR* [192.168.0.61 [1436808628443] GET /sysop.shmodellib.detail HTTP/1.1] org.apache.jackrabbit.core.persistence.pool.Bundle
DbPersistenceManager failed to read bundle (stacktrace on DEBUG log level): 99c4c03d-ec94-4b7b-8161-2dbda0fbef4c: org.postgresql.util.PSQLException: An
 I/O error occurred while sending to the backend.
14.07.2015 01:30:36.793 *ERROR* [192.168.0.61 [1436808628443] GET /sysop.shmodellib.detail HTTP/1.1] org.apache.jackrabbit.core.ItemManager failed to r
etrieve item state of item 99c4c03d-ec94-4b7b-8161-2dbda0fbef4c
org.apache.jackrabbit.core.state.ItemStateException: failed to read bundle (stacktrace on DEBUG log level): 99c4c03d-ec94-4b7b-8161-2dbda0fbef4c: org.p
ostgresql.util.PSQLException: An I/O error occurred while sending to the backend.
        at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.loadBundle(BundleDbPersistenceManager.java:902)
        at org.apache.jackrabbit.core.persistence.bundle.AbstractBundlePersistenceManager.getBundleCacheMiss(AbstractBundlePersistenceManager.java:766)
        at org.apache.jackrabbit.core.persistence.bundle.AbstractBundlePersistenceManager.getBundle(AbstractBundlePersistenceManager.java:749)
        at org.apache.jackrabbit.core.persistence.bundle.AbstractBundlePersistenceManager.load(AbstractBundlePersistenceManager.java:487)
        at org.apache.jackrabbit.core.state.SharedItemStateManager.loadItemState(SharedItemStateManager.java:1869)
        at org.apache.jackrabbit.core.state.SharedItemStateManager.getNonVirtualItemState(SharedItemStateManager.java:1789)
        at org.apache.jackrabbit.core.state.SharedItemStateManager.getItemState(SharedItemStateManager.java:270)
        at org.apache.jackrabbit.core.state.LocalItemStateManager.getNodeState(LocalItemStateManager.java:110)
        at org.apache.jackrabbit.core.state.LocalItemStateManager.getItemState(LocalItemStateManager.java:175)
        at org.apache.jackrabbit.core.state.XAItemStateManager.getItemState(XAItemStateManager.java:260)
        at org.apache.jackrabbit.core.state.SessionItemStateManager.getItemState(SessionItemStateManager.java:161)
```
```
14.07.2015 01:30:36.795 *WARN* [192.168.0.61 [1436808628443] GET /sysop.shmodellib.detail HTTP/1.1] org.apache.jackrabbit.core.query.lucene.NodeIterato
rImpl Failed to retrieve query result node 99c4c03d-ec94-4b7b-8161-2dbda0fbef4c
javax.jcr.RepositoryException: failed to retrieve item state of item 99c4c03d-ec94-4b7b-8161-2dbda0fbef4c
        at org.apache.jackrabbit.core.ItemManager.getItemData(ItemManager.java:388)
        at org.apache.jackrabbit.core.ItemManager.getItem(ItemManager.java:328)
        at org.apache.jackrabbit.core.ItemManager.getItem(ItemManager.java:622)
```
```
14.07.2015 01:30:37.406 *ERROR* [ClusterNode-node0_60] org.apache.jackrabbit.core.util.db.ConnectionHelper Failed to execute SQL (stacktrace on DEBUG log level): org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
14.07.2015 01:30:37.507 *ERROR* [ClusterNode-node0_60] org.apache.jackrabbit.core.util.db.ConnectionHelper Failed to execute SQL (stacktrace on DEBUG log level): org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
14.07.2015 01:30:37.508 *ERROR* [ClusterNode-node0_60] org.apache.jackrabbit.core.cluster.ClusterNode Periodic sync of journal failed: Unable to return record iterator.
org.apache.jackrabbit.core.cluster.ClusterException: Unable to return record iterator.
        at org.apache.jackrabbit.core.cluster.ClusterNode.internalSync(ClusterNode.java:343)
        at org.apache.jackrabbit.core.cluster.ClusterNode.sync(ClusterNode.java:356)
        at org.apache.jackrabbit.core.cluster.ClusterNode.run(ClusterNode.java:303)
```

## Solution

重装0.64，恢复7.13日数据

- [x] 在0.60上恢复pgsql数据
- [x] 在0.60，0.62，0.65上恢复sling数据，并重建索引。
- [x] 在0.60上恢复备份机制 - http://192.168.2.21:8080/view/backup/job/xuanran001_backup_sling/
 - [x] psql dump 
 - [x] Backup ```/home/glue/sling``` dir
- [x] Make 0.64 a new sling cluster node.
- [x] Nagios checking
 - [x] check sling status on 0.60, 0.62, 0.64, 0.65
 - [x] check sling backup status on 0.60

**Comment by xxd3vin** [comment]
Make sure ```scp``` can work from 0.60 to 1.153

**Comment by xxd3vin** [comment]
Make 0.60 a new database server.
