### ISSUE TITLE
job201507160959042544681 failed

### ISSUE THREAD

**Issue by xxd3vin** [xxd3vin/workspace#12]
```
7/16/2015 9:59:02 AM [DEBUG] New job arrived: job201507160959042544681
7/16/2015 9:59:02 AM [DEBUG] wget --mirror ftp://apache:apache@192.168.0.61:21//home/glue/share/repository/9a3c/5233/bebe/4ace/9e7e/cca9/efee/e6c9/input -nH --cut-dirs=14 -P /home/handle/nhandler/temp/input
ESC[0mPOST /dojob ESC[32m200 ESC[0m10.785 ms - 37ESC[0m
7/16/2015 9:59:02 AM [DEBUG] [wget] [event:exit]: status code is 8
7/16/2015 9:59:02 AM [DEBUG] [job201507160959042544681] Worker event [fail].
7/16/2015 9:59:02 AM [DEBUG] [job201507160959042544681] error message: job failed
7/16/2015 9:59:02 AM [DEBUG] curl "http://192.168.2.21:8080/job/chenyang_notification/buildWithParameters?token=sp12345678&title=HandlerError&content=Handler%20IP%3A%20192.168.0.181%0ADetails%3A%20Rendering%20failed%3A%0Ajob%20failed"
7/16/2015 9:59:02 AM [DEBUG] [job201507160959042544681] PUT scheduler:8080/content/sys.jobfailed : job201507160959042544681
7/16/2015 9:59:02 AM [DEBUG] [wget] [event:close]: status code is 8
7/16/2015 9:59:02 AM [DEBUG] [job201507160959042544681] Alternatively, you can use curl to send this PUT request when this request is failed : curl -u admin:admin -X PUT -d "jid=job201506021727113774035" 192.168.0.59:8080/content/sys.jobfinished
7/16/2015 9:59:02 AM [DEBUG] [job201507160959042544681] status code: 200
7/16/2015 9:59:02 AM [DEBUG] [job201507160959042544681] response body: {"message":"good job"}

7/16/2015 9:59:02 AM [DEBUG] [job201507160959042544681] Make me free.
```

**Comment by xxd3vin** [comment]
file not found
```
[root@xuanran001 chenyang]# cd /home/glue/share/repository/9a3c/5233/bebe/4ace/9e7e/cca9/efee/e6c9
bash: cd: /home/glue/share/repository/9a3c/5233/bebe/4ace/9e7e/cca9/efee/e6c9: No such file or directory
```

**Comment by xxd3vin** [comment]
logs in 0.64
```
[2015-7-16 9:57:25][job_create]#渲染参数处理日志: 可用余额为: 486
[2015-7-16 9:57:25][job_create]#渲染参数处理日志: 保存全部渲染信息: {"moment":"afternoon","size":"small","cameraName":["书房"],"unitprice":0,"jobprice"
:0,"priority":"30","samples":"1200","type":"PERSP","pic":"classic","resolution":"480x360","watermark":"true","customerName":"wanghaiqiang@spolo.org","n
otifyEmail":"wanghaiqiang@spolo.org","userJobName":"书房"}
[2015-7-16 9:57:30][job_create]#渲染参数处理日志: 生成任务节点,并且保存参数完成: {"id":"9a3c5233-bebe-4ace-9e7e-cca9efeee6c9","path":"/content/users/_w
anghaiqiang_40spolo.org/renderjobs/job77523","name":"job77523","task":[{"id":"d5fd1fb0-0c9d-491c-9e2c-a74614237253","name":"task_1","path":"/content/us
ers/_wanghaiqiang_40spolo.org/renderjobs/job77523/task_1"}]}
[2015-7-16 9:57:30][job_create]#渲染参数处理日志: /var/www/html/upload/7/0000064267 开始解压所上传的渲染文件: /home/glue/share/repository/9a3c/5233/beb
e/4ace/9e7e/cca9/efee/e6c9/input
[2015-7-16 9:57:30][job_create]#渲染参数处理日志: 执行解压命令 /usr/bin/7za X -y -o/home/glue/share/repository/9a3c/5233/bebe/4ace/9e7e/cca9/efee/e6c9/
input /var/www/html/upload/7/0000064267
[2015-7-16 9:57:30][job_create]#渲染参数处理日志: 渲染资源路径: /home/glue/share/repository/9a3c/5233/bebe/4ace/9e7e/cca9/efee/e6c9/input
[2015-7-16 9:57:30][job_create]#渲染参数处理日志: 任务基本信息处理总共耗时 : 5395 毫秒
启动一个线程来完成渲染任务的后续处理
putfile out ........ : 
[2015-7-16 9:57:30][job_create]#渲染资源处理日志: 开始处理渲染资源...
[2015-7-16 9:57:30][job_create]#渲染资源处理日志: 渲染资源是否完整: true
[2015-7-16 9:57:31][job_create]#渲染资源处理日志: 开始解析render.json,并且准备渲染所需要的资源
[2015-7-16 9:57:31][job_create]#渲染资源处理日志: 模型和材质去重完成. 重新构造render.json
[2015-7-16 9:57:31][job_create]#渲染资源处理日志: 渲染文件备份: /home/glue/share/repository/9a3c/5233/bebe/4ace/9e7e/cca9/efee/e6c9/input/original.json
[2015-7-16 9:57:31][job_create]#渲染资源处理日志: 书房 是否等于 书房 true
[2015-7-16 9:57:31][job_create]#渲染资源处理日志: 开始准备高模文件
```

Something is wrong
````
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
        at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:293)
        at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:378)
        at org.apache.commons.io.FileUtils.iterateFiles(FileUtils.java:396)
        at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:155)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:243)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
        at org.mozilla.javascript.gen.c16760._c34(/apps/util/putfile/job/create.POST.esp:1259)
        at org.mozilla.javascript.gen.c16760.call(/apps/util/putfile/job/create.POST.esp)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at org.mozilla.javascript.gen.c16760._c30(/apps/util/putfile/job/create.POST.esp:1135)
        at org.mozilla.javascript.gen.c16760.call(/apps/util/putfile/job/create.POST.esp)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at org.mozilla.javascript.gen.c16760._c24(/apps/util/putfile/job/create.POST.esp:924)
        at org.mozilla.javascript.gen.c16760.call(/apps/util/putfile/job/create.POST.esp)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at org.mozilla.javascript.gen.c16760._c19(/apps/util/putfile/job/create.POST.esp:796)
        at org.mozilla.javascript.gen.c16760.call(/apps/util/putfile/job/create.POST.esp)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at org.mozilla.javascript.gen.c16760._c18(/apps/util/putfile/job/create.POST.esp:719)
        at org.mozilla.javascript.gen.c16760.call(/apps/util/putfile/job/create.POST.esp)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:2834)
        at org.mozilla.javascript.gen.c16760.call(/apps/util/putfile/job/create.POST.esp)
        at org.mozilla.javascript.Context.call(Context.java:548)
        at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:507)
        at adapter1.run(<adapter>)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)
```

**Comment by xxd3vin** [comment]
Remove 0.64 from cluster

**Comment by xxd3vin** [comment]
There is logger demo

```sysop.demo.log```

**Comment by xxd3vin** [comment]
Put some logs

**Comment by xxd3vin** [comment]
https://commons.apache.org/proper/commons-io/apidocs/src-html/org/apache/commons/io/FileUtils.html

```
604    /**
605     * Allows iteration over the files in given directory (and optionally
606     * its subdirectories).
607     * <p>
608     * All files found are filtered by an IOFileFilter. This method is
609     * based on {@link #listFiles(File, IOFileFilter, IOFileFilter)},
610     * which supports Iterable ('foreach' loop).
611     * <p>
612     * @param directory  the directory to search in
613     * @param fileFilter  filter to apply when finding files.
614     * @param dirFilter  optional filter to apply when finding subdirectories.
615     * If this parameter is {@code null}, subdirectories will not be included in the
616     * search. Use TrueFileFilter.INSTANCE to match all directories.
617     * @return an iterator of java.io.File for the matching files
618     * @see org.apache.commons.io.filefilter.FileFilterUtils
619     * @see org.apache.commons.io.filefilter.NameFileFilter
620     * @since 1.2
621     */
622    public static Iterator<File> iterateFiles(
623            final File directory, final IOFileFilter fileFilter, final IOFileFilter dirFilter) {
624        return listFiles(directory, fileFilter, dirFilter).iterator();
625    }
```

```
        var collectionfile = Packages.org.apache.commons.io.FileUtils
            .iterateFiles(srcFile, stuff, false);
```

**Comment by xxd3vin** [comment]
ticket:15163
