### ISSUE TITLE
Syntax error while reading user.json

### ISSUE THREAD

**Issue by xxd3vin** [xxd3vin/workspace#17]
```
7/16/2015 5:49:54 PM [DEBUG] [job20150716163803789257:192.168.0.177] [render.py] [event:close]: status code is 0
7/16/2015 5:49:54 PM [DEBUG] [ls -l 0000.png] STDOUT: 
-rw-r--r-- 1 root root 236430 7月  16 17:49 /home/handle/nhandler/temp/output/0000.png

7/16/2015 5:49:54 PM [DEBUG] [ls -l 0000.png] [event:exit] exit code: 0

undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /home/handle/nhandler/modules/worker/blender.js:245:45
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by xxd3vin** [comment]
Lots of files are invalid
```
7/16/2015 5:49:51 PM [DEBUG] [ls -l input] STDOUT: 
总用量 13248
-rw-r--r-- 1 root root       0 5月  25 06:40 033c41b0-b280-42f1-9993-de2a84e7d948.blend
-rw-r--r-- 1 root root       0 5月  28 02:33 04d1aa67-b9cf-4173-ba0d-10abcf03f7c0.blend
-rw-r--r-- 1 root root       0 4月  29 06:46 0773bb4b-8a21-4fe5-84b3-48a55b47fa31.blend
-rw-r--r-- 1 root root       0 9月  28 2014 0aa58461-2dcc-48bb-8128-5a33d97c56dd.blend
-rw-r--r-- 1 root root       0 6月   9 05:01 1300aa9c-eec7-4624-87e8-0c065b024de6.blend
-rw-r--r-- 1 root root       0 6月   3 08:46 146994aa-9498-45fb-b15c-ace581220827.blend
-rw-r--r-- 1 root root       0 6月   4 04:54 155492bc-b717-4ce5-95d7-3f9d0f5ac15b.blend
-rw-r--r-- 1 root root       0 5月   6 07:19 1d35f002-a0d3-487e-8bf7-2c57846e91d8.blend
-rw-r--r-- 1 root root       0 7月   6 04:26 1efb7cd2-0b6f-4213-b2cd-9a1e5fe28cc7.blend
```

```
-rw-r--r-- 1 root root       5 7月  16 17:49 flag.txt
-rw-r--r-- 1 root root       0 7月  16 08:12 house.sh3d
-rw-r--r-- 1 root root 4269040 7月  16 17:49 main2.blend
-rw-r--r-- 1 root root 4269040 7月  16 17:49 main2.blend1
-rw-r--r-- 1 root root  634644 7月  16 17:49 main.blend
-rw-r--r-- 1 root root 4269040 7月  16 17:49 main.blend1
-rw-r--r-- 1 root root       0 7月  16 08:12 original.json
-rw-r--r-- 1 root root  104081 7月  16 08:12 render.json
-rw-r--r-- 1 root root       0 7月  16 08:12 render.mtl
-rw-r--r-- 1 root root       0 7月  16 08:12 render.obj
drwxr-xr-x 2 root root    4096 7月  16 17:49 textures
-rw-r--r-- 1 root root       0 7月  16 08:12 topcamera.jpg
-rw-r--r-- 1 root root       0 7月  16 08:12 topview.jpg
-rw-r--r-- 1 root root       0 7月  16 08:13 user.json
```

**Comment by xxd3vin** [comment]
```
[root@xuanran001 input]# ll
total 104
-rw-r--r-- 1 apache apache      0 May 25 14:40 033c41b0-b280-42f1-9993-de2a84e7d948.blend
-rw-r--r-- 1 apache apache      0 May 28 10:33 04d1aa67-b9cf-4173-ba0d-10abcf03f7c0.blend
-rw-r--r-- 1 apache apache      0 Apr 29 14:46 0773bb4b-8a21-4fe5-84b3-48a55b47fa31.blend
-rw-r--r-- 1 apache apache      0 Sep 28  2014 0aa58461-2dcc-48bb-8128-5a33d97c56dd.blend
-rw-r--r-- 1 apache apache      0 Jun  9 13:01 1300aa9c-eec7-4624-87e8-0c065b024de6.blend
-rw-r--r-- 1 apache apache      0 Jun  3 16:46 146994aa-9498-45fb-b15c-ace581220827.blend
-rw-r--r-- 1 apache apache      0 Jun  4 12:54 155492bc-b717-4ce5-95d7-3f9d0f5ac15b.blend
-rw-r--r-- 1 apache apache      0 May  6 15:19 1d35f002-a0d3-487e-8bf7-2c57846e91d8.blend
-rw-r--r-- 1 apache apache      0 Jul  6 12:26 1efb7cd2-0b6f-4213-b2cd-9a1e5fe28cc7.blend
-rw-r--r-- 1 apache apache      0 Jun 30 14:22 20400f09-7a2c-41ac-a584-3525e91d8cf3.blend
-rw-r--r-- 1 apache apache      0 Jan 28 14:10 24484fca-91e7-4c37-9cd2-a35d78ec52f1.blend
-rw-r--r-- 1 apache apache      0 Jul  6 18:33 2a7c8951-27b8-4610-89c8-4ced9032510a.blend
-rw-r--r-- 1 apache apache      0 Jun  2 15:59 2eb251a9-9129-47a4-b170-ed8c5c98eb18.blend
-rw-r--r-- 1 apache apache      0 Jun  3 16:49 38a14512-3143-473f-9569-25d1575b4af3.blend
-rw-r--r-- 1 apache apache      0 Jun  4 10:43 3998e0ac-6fd9-4e3c-9835-75cfc28cd64f.blend
-rw-r--r-- 1 apache apache      0 Jun  4 10:29 3c08a212-1f21-4e6b-8541-b5af3910102e.blend
-rw-r--r-- 1 apache apache      0 Jun 19 11:15 4512428a-fe45-4d27-83bb-0d42c964652f.blend
-rw-r--r-- 1 apache apache      0 Jun  9 17:11 4592fe75-e4a5-44d1-8ff3-8c1ba6d2f033.blend
-rw-r--r-- 1 apache apache      0 Jun  3 16:29 4e030704-ef4c-4a65-a35a-06ca54741839.blend
-rw-r--r-- 1 apache apache      0 Jun  5 10:56 4f9d586f-7baf-4d40-8442-9c5a11cee368.blend
-rw-r--r-- 1 apache apache      0 May 15 14:25 502cc3b9-5557-45ef-94c7-e855c7dced73.blend
-rw-r--r-- 1 apache apache      0 Apr 10  2014 677a155b-9a03-493d-b79a-953f08ca6586.blend
-rw-r--r-- 1 apache apache      0 Jun 19 11:20 696036d5-c3ec-423e-88f5-8e57d23aea7f.blend
-rw-r--r-- 1 apache apache      0 May 26 18:11 758ca8f7-a9de-460e-8014-c8bd3980fe1f.blend
-rw-r--r-- 1 apache apache      0 Apr 10  2014 7e3a8f50-5a71-4933-ab0d-b18dad7ae65c.blend
-rw-r--r-- 1 apache apache      0 Dec  5  2014 8515e72a-fa46-4d0c-9682-3c57edb5cae1.blend
-rw-r--r-- 1 apache apache      0 May 12 13:10 87c861bf-20c8-492d-81a5-1983be783c6a.blend
-rw-r--r-- 1 apache apache      0 May 15 16:33 8a357b97-7ab3-4b32-bc6f-dc0b3a6bdbfd.blend
-rw-r--r-- 1 apache apache      0 Jun  1 15:02 93fd6335-dae7-47ce-bb55-0b4b3e2c9151.blend
-rw-r--r-- 1 apache apache      0 May 29 15:02 a3918501-a830-46be-bee0-042e3f137e6f.blend
-rw-r--r-- 1 apache apache      0 Jun 18 15:52 aa423805-2bc1-467d-90b8-3160ac6a9aea.blend
-rw-r--r-- 1 apache apache      0 Jun  3 17:13 ae0bc451-6e33-4848-b1e3-b780e5cb0d1a.blend
-rw-r--r-- 1 apache apache      0 Sep 30  2014 b25166b3-6723-4b52-89ca-92e361c05a89.blend
-rw-r--r-- 1 apache apache      0 Dec 12  2013 b6a1b658-df24-47c3-8029-402c91e642ed.blend
-rw-r--r-- 1 apache apache      0 Jul 16 16:12 background.jpg
-rw-r--r-- 1 apache apache      0 May 28 14:33 c06b8baf-db89-4d02-ab7d-b3638fea62cf.blend
-rw-r--r-- 1 apache apache      0 May 29 15:09 d1a540e5-d477-4f9d-a201-ac35c8b0cf97.blend
-rw-r--r-- 1 apache apache      0 Jan  6  2015 d698448f-556b-4d92-9226-4548647197cd.blend
-rw-r--r-- 1 apache apache      0 May 12 17:53 e52d7fda-40d7-4b20-9efb-2ddaac9a6a2c.blend
-rw-r--r-- 1 apache apache      0 May  6 17:08 eb69bd8f-1e59-4b5d-8717-100e842d639f.blend
-rw-r--r-- 1 apache apache      0 Jun 10 14:51 ebc44ea2-0dc0-4ed5-ba20-3ffeb4bdce97.blend
-rw-r--r-- 1 apache apache      0 Apr 28 15:26 ee36cdf6-b7d0-410d-b354-7478219f3568.blend
-rw-r--r-- 1 apache apache      0 May 21 15:12 faa2feb2-8389-489c-a1aa-627ebcc883fc.blend
-rw-r--r-- 1 apache apache      0 Jan 21  2014 fec70159-5e49-4189-92b2-085b1b90929d.blend
-rw-r--r-- 1 apache apache      0 Jul 16 16:12 house.sh3d
-rw-r--r-- 1 apache apache      0 Jul 16 16:12 original.json
-rw-r--r-- 1 apache apache 104081 Jul 16 16:12 render.json
-rw-r--r-- 1 apache apache      0 Jul 16 16:12 render.mtl
-rw-r--r-- 1 apache apache      0 Jul 16 16:12 render.obj
-rw-r--r-- 1 apache apache      0 Jul 16 16:12 topcamera.jpg
-rw-r--r-- 1 apache apache      0 Jul 16 16:12 topview.jpg
-rw-r--r-- 1 apache apache      0 Jul 16 16:13 user.json
```

**Comment by xxd3vin** [comment]
Try catch when parse json string.
