### ISSUE TITLE
Handler got error message when registering on scheduler

### ISSUE THREAD

**Issue by xxd3vin** [xxd3vin/workspace#6]
## Summary

```
REQUEST emitting complete http://192.168.0.59:8080/content/sys.register
7/14/2015 4:15:46 PM [DEBUG] <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 NOT_FOUND</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /content/sys.register. Reason:
<pre>    NOT_FOUND</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>

7/14/2015 4:15:46 PM [DEBUG] Exception in parsing response body, message: Unexpected token <
7/14/2015 4:15:46 PM [DEBUG] undefined
7/14/2015 4:15:46 PM [DEBUG] curl "http://192.168.2.21:8080/job/chenyang_notification/buildWithParameters?token=sp12345678&title=HandlerError&content=Handler%20IP%3A%20192.168.0.174%0ADetails%3A%20Register%20failed"
7/14/2015 4:15:46 PM [DEBUG] Register handler failed, exit now..Please check and try again
```

## Solution

Check response and retry on ```sys.register```

**Comment by xxd3vin** [comment]
Try this module https://github.com/FGRibreau/node-request-retry

**Comment by xxd3vin** [comment]
Need a testing env.

**Comment by xxd3vin** [comment]
Need a testing scheduler

**Comment by xxd3vin** [comment]
Sling restart at this time

```
10.08.2015 12:21:02.509 *INFO* [main] Setting sling.home=/home/glue/sling (command line)
10.08.2015 12:21:02.510 *INFO* [main] Starting Sling in /home/glue/sling
10.08.2015 12:21:02.511 *ERROR* [Sling Control Listener@/192.168.0.59:80] Failed to start Sling Control Server
java.net.BindException: Permission denied
10.08.2015 12:21:02.511 *ERROR* [Sling Control Listener@/192.168.0.59:80]       at java.net.PlainSocketImpl.socketBind(Native Method)
10.08.2015 12:21:02.511 *ERROR* [Sling Control Listener@/192.168.0.59:80]       at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:383)
10.08.2015 12:21:02.511 *ERROR* [Sling Control Listener@/192.168.0.59:80]       at java.net.ServerSocket.bind(ServerSocket.java:328)
10.08.2015 12:21:02.511 *ERROR* [Sling Control Listener@/192.168.0.59:80]       at java.net.ServerSocket.bind(ServerSocket.java:286)
10.08.2015 12:21:02.511 *ERROR* [Sling Control Listener@/192.168.0.59:80]       at org.apache.sling.launchpad.app.ControlListener.run(ControlListener.java:141)
10.08.2015 12:21:02.511 *ERROR* [Sling Control Listener@/192.168.0.59:80]       at java.lang.Thread.run(Thread.java:662)
10.08.2015 12:21:02.517 *INFO* [main] Checking launcher JAR in folder /home/glue/sling
10.08.2015 12:21:02.526 *INFO* [main] Existing launcher is up to date, using it: 2.3.0 (org.apache.sling.launchpad.base.jar)
10.08.2015 12:21:02.527 *INFO* [main] Loading launcher class org.apache.sling.launchpad.base.app.MainDelegate from org.apache.sling.launchpad.base.jar
10.08.2015 12:21:02.536 *INFO* [main] Starting launcher ...
10.08.2015 12:21:02.538 *INFO* [main] HTTP server port: 8080
10.08.2015 12:21:02.923 *INFO* [main] Startup completed
2015-08-10 04:21:03.350 GMT Thread[FelixStartLevel,5,main] java.io.FileNotFoundException: derby.log (Permission denied)
----------------------------------------------------------------
2015-08-10 04:21:03.861 GMT:
 Booting Derby version The Apache Software Foundation - Apache Derby - 10.5.3.0 - (802917): instance a816c00e-014f-15d7-1cf7-0000f1a4d350
on database directory /home/glue/sling/jackrabbit/version/db  

Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
2015-08-10 04:21:04.445 GMT:
 Booting Derby version The Apache Software Foundation - Apache Derby - 10.5.3.0 - (802917): instance 594b8034-014f-15d7-1cf7-0000f1a4d350
on database directory /home/glue/sling/jackrabbit/workspaces/default/db  

Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
2015-08-10 04:21:08.326 GMT:
 Booting Derby version The Apache Software Foundation - Apache Derby - 10.5.3.0 - (802917): instance cbe9405a-014f-15d7-1cf7-0000f1a4d350
on database directory /home/glue/sling/jackrabbit/workspaces/security/db  

Database Class Loader started - derby.database.classpath=''
glue bundle started.
Restarting file (/tmp/glue-service-is-restarting-now) was deleted successfully
```

**Comment by xxd3vin** [comment]
Try after 30s
```
    setTimeout(function() {
      utils.xlog("Starting retry registering.");
      handler.register( register_callback );
    }, 30000);
```
